apiVersion: v1
kind: Service
metadata:
  name: ci-demo
spec:
  selector:
    app: ci-demo
  type: NodePort
  ports:
    - port: 8888
      nodePort: 32256
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo
  labels:
    app: ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-demo
  template:
    metadata:
      labels:
        app: ci-demo
    spec:
      imagePullSecrets:
        - name: ci-demo
      containers:
        - name: ci-demo
          image: registry.cn-beijing.aliyuncs.com/fengshunli/ci-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888